### ISSUE TITLE
Benefits to using NhCacheJsonSerialiser

### ISSUE THREAD

**Issue by paulduran** [TheCloudlessSky/NHibernate.Caches.Redis#18]
I'm just in the process of upgrading our NHibernate.Caches.Redis from quite an old version that used the ServiceStack.Redis client.

I'm reading through the README and it mentions that it's possible to switch serialisers to, for example, the NhCacheJsonSerialiser.

I was just wondering if you could explain the benefits/drawbacks of doing so? Would it be more performant?

**Comment by TheCloudlessSky** [comment]
For JSON serializer:
1. XML will have a larger serialization size than JSON (meaning more memory used in Redis).
2. Depending on your serializer, JSON can be significantly faster (the built in DataContractSerializer is pretty slow).
3. Redis has [built-in support for JSON reading/writing via Lua scripts](http://redis.io/commands/EVAL) in case you wanted to manually poke around the JSON with a Lua script (although I've never needed to do this).
4. You may not like XML?

The one thing that sucks about NHibernate's caching interface is that they don't expose the type to the `ICache`. This means you have to store the type information *with* the serialized data so you know how to deserialize it. But, allowing you to use

**Comment by paulduran** [comment]
Thanks! Appreciate your response on this.

**Comment by TheCloudlessSky** [comment]
No problem :smile:
