### ISSUE TITLE
Nhibernate 5 chacged ICache interface adding async methods Nhibernate.Caches.Redis fails with it

### ISSUE THREAD

**Issue by uciprian** [TheCloudlessSky/NHibernate.Caches.Redis#32]
Nhibernate 5 chacged ICache interface adding async methods Nhibernate.Caches.Redis fails with it.
You'll get the following error trying to use this cache provider

System.TypeLoadException: Method 'GetAsync' in type 'NHibernate.Caches.Redis.RedisCache' from assembly 'NHibernate.Caches.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by TheCloudlessSky** [comment]
Hi @uciprian - see #31 for this.
