### ISSUE TITLE
Not implement exception with method 'GetAsync'

### ISSUE THREAD

**Issue by futurify-ydang** [TheCloudlessSky/NHibernate.Caches.Redis#36]
I am using NHibernate.Cache.Redis for my project in .NET Core 2.2 and faced this exception.
Please give me a help! 
Thanks
```System.TypeLoadException: Method 'GetAsync' in type 'NHibernate.Caches.Redis.RedisCache' from assembly 'NHibernate.Caches.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.```

And another question is does **NHibernate.Caches.Redis** support .NET core?

**Comment by TheCloudlessSky** [comment]
See #31, #32, #33 for NHibernate >= 5 issues (the not implemented exception). I have not tested this project with .NET Core, so I'm not sure if it works.

**Comment by futurify-ydang** [comment]
![image](https://user-images.githubusercontent.com/44663784/53852473-bbfcfc80-3ff4-11e9-8ef6-c48e5267c0f6.png)
its working well in aspnet core 2.2 .
The only one thing need to do is custom a serializer for us. Because **NetDataContractCacheSerializer** was not still exist in Net Core

**Comment by futurify-ydang** [comment]
The exception has been thrown. Any ideas?
![image](https://user-images.githubusercontent.com/44663784/53853857-bf46b700-3ff9-11e9-95c1-c1263816e032.png)
