### ISSUE TITLE
"An existing connection was forcibly closed by the remote host" after restarting Redis

### ISSUE THREAD

**Issue by kowalgta** [TheCloudlessSky/NHibernate.Caches.Redis#4]
I'm getting an exception after restarting Redis:
[SocketException (0x2746): An existing connection was forcibly closed by the remote host]
   System.Net.Sockets.Socket.Send(IList`1 buffers, SocketFlags socketFlags) +3094587
   ServiceStack.Redis.RedisNativeClient.FlushSendBuffer() +118
   ServiceStack.Redis.RedisTransaction.Commit() +553

I'm using PooledRedisClientManager, using BasicRedisClientManager helps a little (got this exception on the first request only, subsequent were fine).

I believe that this provider should be more robust and handle exceptions like this by simply returning nothing from the cache so NHibernate can still operate and execute regular query.

Any thoughts ?

**Comment by TheCloudlessSky** [comment]
@kowalgta I'm going to close this due to lack of activity. Also, I just pushed the 2.0 release which now uses StackExchange.Redis as the Redis provider. Please give it a shot and let me know if you have any problems.
